#!/usr/bin/python2.7

class DataBaseException(Exception):
    def __init__(self): pass
